language: node_js
node_js:
  - '10'
before_install:
  - npm install -g firebase-tools
install:
  - yarn install
script:
  - npm test
after_success:
  - firebase deploy --project headstrong-dev --token $FIREBASE_TOKEN
