export const USERS_SET = 'USERS_SET',
  USER_SET = 'USER_SET',
  AUTH_USER_SET = 'AUTH_USER_SET',
  MESSAGES_SET = 'MESSAGES_SET',
  MESSAGES_LIMIT_SET = 'MESSAGES_LIMIT_SET',
  LOAD_PAGES_SUCCESS = 'LOAD_PAGES_SUCCESS',
  LOAD_PAGE_SUCCESS = 'LOAD_PAGE_SUCCESS',
  CLEAR_PAGE_SUCCESS = 'CLEAR_PAGE_SUCCESS';
